version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hokeytrainer
    entrypoint: bin/run.sh
    # stdin_open: true
    # tty: true
    ports:
      - 8998:8080
    restart: always
    labels:
      - "traefik.http.routers.hockey.rule=Host(`hockey.local.seanhome.xyz`)"
      - "traefik.http.services.hockey.loadbalancer.server.port=8080"
    volumes:
      - ./configs:/etc/configs/

# networks:
#   default:
#     external:
#       name: traefik_default
#volumes:
#  configs: